# Generated by Django 5.2.6 on 2025-09-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nasc', models.DateField()),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(max_length=14, unique=True)),
                ('sexo', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('telefone2', models.CharField(max_length=11, unique=True)),
                ('cep', models.CharField(max_length=8)),
                ('endereco', models.CharField(max_length=250)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.BooleanField(default=True)),
                ('matricula', models.IntegerField(max_length=30)),
                ('curso', models.CharField(max_length=150)),
                ('serie', models.CharField(max_length=150)),
                ('ano', models.CharField(max_length=150)),
                ('turno', models.CharField(max_length=150)),
                ('obersvacoes', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
