# Generated by Django 5.2.6 on 2025-09-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_alter_aluno_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='obersvacoes',
        ),
        migrations.AddField(
            model_name='aluno',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ano',
            field=models.CharField(choices=[('1', '1º Ano'), ('2', '2º Ano'), ('3', '3º Ano'), ('4', '4º Ano')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='numero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='telefone2',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('I', 'Integral')], max_length=1),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf',
            field=models.CharField(choices=[('RN', 'Rio Grande do Norte'), ('CE', 'Ceará'), ('PB', 'Paraíba')], max_length=2),
        ),
    ]
