# Generated by Django 5.2.4 on 2025-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0003_remove_aluno_obersvacoes_aluno_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='ano',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='serie',
            field=models.CharField(choices=[('1º Ano', '1º Ano'), ('2º Ano', '2º Ano'), ('3º Ano', '3º Ano'), ('4º Ano', '4º Ano')], max_length=6),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='turno',
            field=models.CharField(choices=[('Manhã', 'Manhã'), ('Tarde', 'Tarde'), ('Noite', 'Noite'), ('Integral', 'Integral')], max_length=15),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='uf',
            field=models.CharField(choices=[('RN', 'Rio Grande do Norte'), ('CE', 'Ceará'), ('PB', 'Paraíba')], max_length=80),
        ),
    ]
