# Generated by Django 5.2.4 on 2025-09-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0004_remove_aluno_ano_alter_aluno_serie_alter_aluno_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.CharField(choices=[('Alimentos', 'Alimentos'), ('Apicultura', 'Apicultura'), ('Informática', 'Informática')], max_length=150),
        ),
    ]
