# Generated by Django 5.2.6 on 2025-09-19 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='uf',
            field=models.CharField(choices=[('RN', 'RN'), ('CE', 'CE'), ('PB', 'PB')], max_length=2),
        ),
    ]
